version: '3.8'
services:
  backend:
    build: "./ilia-api/"
    ports:
      - "7289:7289"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=anthony
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx

  frontend:
    build: "./ilia"
    env_file:
      - ./ilia/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
